### ISSUE TITLE
Java version of Alien Dictionary has minor issue

### ISSUE THREAD

**Issue by w22116972** [ndesai15/coding-java#12]
https://github.com/ndesai15/coding-java/blob/master/src/com/coding/patterns/topologicalsort/AlienDictionary.java

In line 7

If `words` is really `null`, then `words.length` will throw `NullPointerException` **first** **before** checking whether it is null or not.

So either we assume all given words is non-null or we change the order like `if (words == null || words.length ...)`

**Comment by ndesai15** [comment]
Good catch. I've fixed code and pushed to master.
