### ISSUE TITLE
SearchInRotatedSortedArray.java

### ISSUE THREAD

**Issue by javaspeak** [ndesai15/coding-java#13]
SearchInRotatedSortedArray.java fails for data:

    int result = searchInRotatedSortedArray.search( new int[] { 5, 1, 3 }, 2 );
    Assert.assertEquals( result, -1 );

It does not return and times out

 Code on line 30:

     left = mid - 1;

should be changed to 

     left = mid + 1;

**Comment by ndesai15** [comment]
Corrected. Please pull latest code. thanks
