### ISSUE TITLE
Coin change answer is incorrect

### ISSUE THREAD

**Issue by bartboersma** [ndesai15/coding-java#17]
Hi,

I noticed that the coin change answer is incorrect: https://github.com/ndesai15/coding-java/blob/master/src/com/coding/patterns/dynamicprogramming/knapsack/unbounded/CoinChange.java. The example coins = [2], amount = 3 should result in -1. This code would return 4.

Leetcode issue: https://leetcode.com/problems/coin-change/

**Comment by ndesai15** [comment]
Corrected with my submitted solution in LC. Please clone latest master.
