### ISSUE TITLE
Koko Eating Bananas Answer Incorrect

### ISSUE THREAD

**Issue by XiangXu** [ndesai15/coding-java#26]
Currently Answer will fail with below test case:
```
[805306368,805306368,805306368]
1000000000
```

I think we need to change count method return type from int to long to make it work.

```java
  private long count(int[] piles, int k) {
        long result = 0;
        for(int pile : piles) {
            result += (pile / k) + (pile % k == 0 ? 0 : 1);
        }
        return result;
    }
```

**Comment by ndesai15** [comment]
Looks like LC has updated their test cases. I've updated code & not it is getting passed for all test cases. Please pull latest master.

**Comment by XiangXu** [comment]
That is great, thank you!!
