### ISSUE TITLE
AlienDictionary does not work on https://www.lintcode.com/problem/892/

### ISSUE THREAD

**Issue by javaspeak** [ndesai15/coding-java#27]
I do not have premium access to AlienDictonary on leetcode.   I think this solution is for leetcode.

The wording of the question on lintcode is different to the wording of the question on leetcode (I think).

The lintcode wording on https://www.lintcode.com/problem/892/ includes:

      "There may be multiple valid order of letters, return the smallest in normal lexicographical order."

The Java AlienDictionary solution does not cater for this.

The code looks like:

    StringBuilder sortedOrder = new StringBuilder();

    while (!sources.isEmpty()) {
            Character vertex = sources.remove();
            sortedOrder.append(vertex);
            for (char c: graph.get(vertex)) {
                inDegree.put(c, inDegree.get(c) - 1);
                if (inDegree.get(c) == 0) {
                    sources.add(c);
                }
            }
        }

Notice there is no sorting going on with the StringBuilder

I think that the main problem you have is that on:

     needcode.io blind75 Advanced Graph - Alien Dictionary

the Alien Dictionary link goes to:

     https://www.lintcode.com/problem/892/

while the Java Solution is for leetcode which is locked and is only available for premium members.

I think it will help others if this is somehow conveyed to the readers of needcode.io, blind75,  Advanced Graph - Alien Dictionary

Thank you

**Comment by ndesai15** [comment]
Thanks for dragging my attention to this. Usually I mention a leetcode problem link to the top of solution which I completely missed in this problem. I have updated my solution with a link to LC problem.
