### ISSUE TITLE
Issue in minstack 

### ISSUE THREAD

**Issue by Rishiyananthan** [ndesai15/coding-java#3]
https://github.com/ndesai15/coding-java/blob/master/src/com/coding/patterns/stacks/MinStack.java

Bug:
 public void push(int val) {
        stack.push(val);
        if (minStack.isEmpty() || val <= minStack.peek()) {
            minStack.push(val);
        }
    }

Fix:
 public void push(int val) {
        stack.push(val);
        if(minstack.isEmpty()||val<minstack.peek()){
            minstack.push(val);
        }
        else{
            minstack.push(minstack.peek());
        }
    }

**Comment by ndesai15** [comment]
I am not sure how this is a bug for you because this solution is accepted on leetcode without any issue.

**Comment by ndesai15** [comment]
Closing this out as existing implementation still aligns with leetcode acceptance criteria.
