### ISSUE TITLE
Typo in BalancedBinaryTree

### ISSUE THREAD

**Issue by vuhctreh** [ndesai15/coding-java#30]
https://github.com/ndesai15/coding-java/blob/master/src/com/coding/patterns/tree/BalancedBinaryTree.java

The ```isBalance``` method in the linked solution does not work (the method should be called ```isBalanced```).

**Comment by ndesai15** [comment]
Hello @vuhctreh , Can you point me to a place where you found `isBalanced` word in solution?

**Comment by vuhctreh** [comment]
Hi @ndesai15, you can see the method on leetcode: 
https://leetcode.com/problems/balanced-binary-tree/

**Comment by ndesai15** [comment]
To be honest with you, I wouldn't bother about it. Please let me know if you have any other concerns.

Feel Free to look into other open issues & help others by contributing to this repo!
