### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by reidiculous93** [ndesai15/coding-java#4]
Solution code here returns Runtime Error when submitting. 
java.util.EmptyStackException
  at line 101, java.base/java.util.Stack.peek
  at line 27, MinStack.getMin
  at line 72, __Driver__.__helperSelectMethod__
  at line 90, __Driver__.__helper__
  at line 111, __Driver__.main

Below code resolves the issue: 
class MinStack {
    
    private Stack<int[]> stack = new Stack<>();
    
    public MinStack() {
    }
    
    public void push(int val) {
        
        if (stack.isEmpty()) {
            stack.push(new int[]{val, val});
            return;
        }
        int currentMin = stack.peek()[1];
        stack.push(new int[]{val, Math.min(val, currentMin)});
    }
    
    public void pop() {
        stack.pop();
    }
    
    public int top() {
        return stack.peek()[0];
    }
    
    public int getMin() {
        return stack.peek()[1];
    }
}

**Comment by ndesai15** [comment]
Indeed. My repo had a buggy code while leetcode UI had a working solution. I updated my master. it should be good now.Thank you.
